import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { LogbookEntry } from "@/types";

interface PDFExportOptions {
  apprenticeName: string;
  dateRange?: { start: string; end: string };
  siteName?: string;
  organizationName?: string;
}

/**
 * Generate a BCITO-formatted PDF from logbook entries.
 * Works both client-side and server-side (Node).
 */
export function generateBCITOPdf(
  entries: LogbookEntry[],
  options: PDFExportOptions
): jsPDF {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // --- Header ---
  doc.setFillColor(249, 115, 22); // orange-500
  doc.rect(0, 0, pageWidth, 32, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Apprentice Log", 14, 14);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("BCITO Logbook Export", 14, 22);

  // Date & name on right
  doc.setFontSize(9);
  const exportDate = new Date().toLocaleDateString("en-NZ", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  doc.text(`Generated: ${exportDate}`, pageWidth - 14, 14, { align: "right" });

  // --- Info Section ---
  let y = 40;
  doc.setTextColor(55, 65, 81); // gray-700
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Apprentice:", 14, y);
  doc.setFont("helvetica", "normal");
  doc.text(options.apprenticeName, 50, y);

  if (options.organizationName) {
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.text("Employer:", 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(options.organizationName, 50, y);
  }

  if (options.dateRange) {
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.text("Period:", 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(
      `${formatDate(options.dateRange.start)} — ${formatDate(options.dateRange.end)}`,
      50,
      y
    );
  }

  if (options.siteName) {
    y += 6;
    doc.setFont("helvetica", "bold");
    doc.text("Site:", 14, y);
    doc.setFont("helvetica", "normal");
    doc.text(options.siteName, 50, y);
  }

  // --- Summary Stats ---
  const totalHours = entries.reduce(
    (sum, e) => sum + (e.totalHours || e.hours || 0),
    0
  );
  const totalEntries = entries.length;

  y += 10;
  doc.setFillColor(255, 247, 237); // orange-50
  doc.roundedRect(14, y, pageWidth - 28, 14, 2, 2, "F");
  doc.setFontSize(9);
  doc.setTextColor(154, 52, 18); // orange-800
  doc.setFont("helvetica", "bold");
  doc.text(`Total Entries: ${totalEntries}`, 20, y + 6);
  doc.text(`Total Hours: ${totalHours}`, 80, y + 6);
  doc.text(
    `Avg Hours/Entry: ${totalEntries > 0 ? (totalHours / totalEntries).toFixed(1) : "0"}`,
    140,
    y + 6
  );

  y += 20;

  // --- Entries Table ---
  const tableBody = entries.map((entry) => {
    const tasks = (entry.tasks || [])
      .map((t) => t.description)
      .join("\n");
    const hours = entry.totalHours || entry.hours || 0;
    const tools = [
      ...new Set((entry.tasks || []).flatMap((t) => t.tools || [])),
    ].join(", ");
    const skills = [
      ...new Set((entry.tasks || []).flatMap((t) => t.skills || [])),
    ].join(", ");
    const safety = entry.safetyObservations || "";

    return [
      formatDate(entry.date),
      tasks,
      `${hours}`,
      tools,
      skills,
      safety,
    ];
  });

  autoTable(doc, {
    startY: y,
    head: [["Date", "Tasks", "Hours", "Tools", "Skills", "Safety"]],
    body: tableBody,
    theme: "grid",
    headStyles: {
      fillColor: [249, 115, 22], // orange-500
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 7,
      textColor: [55, 65, 81],
      cellPadding: 2,
    },
    columnStyles: {
      0: { cellWidth: 22 },   // Date
      1: { cellWidth: 50 },   // Tasks
      2: { cellWidth: 14 },   // Hours
      3: { cellWidth: 30 },   // Tools
      4: { cellWidth: 30 },   // Skills
      5: { cellWidth: 30 },   // Safety
    },
    alternateRowStyles: {
      fillColor: [255, 247, 237], // orange-50
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      // Footer on each page
      const pageCount = doc.getNumberOfPages();
      doc.setFontSize(7);
      doc.setTextColor(156, 163, 175); // gray-400
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 8,
        { align: "center" }
      );
      doc.text(
        "Generated by Apprentice Log — apprenticelog.nz",
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 4,
        { align: "center" }
      );
    },
  });

  return doc;
}

/**
 * Generate and trigger download of a BCITO PDF.
 */
export function downloadBCITOPdf(
  entries: LogbookEntry[],
  options: PDFExportOptions
) {
  const doc = generateBCITOPdf(entries, options);
  const filename = buildFilename(options);
  doc.save(filename);
}

function buildFilename(options: PDFExportOptions): string {
  const parts = ["apprentice-log"];
  if (options.dateRange) {
    parts.push(options.dateRange.start, "to", options.dateRange.end);
  }
  return `${parts.join("-")}.pdf`;
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString("en-NZ", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch {
    return dateStr;
  }
}
